---

- name: VLAN SETUP
  hosts: TC2-LIDC-Nexus-Layer3
  connection: local
  gather_facts: yes

  tasks:
   - name: VLAN SETUP
     nxos_config:
      transport: cli
      lines:
       - name OT
      parents:
       - vlan 2999
      host: TC2-LIDC-Nexus-Layer3
      username: admin
      password: admin
